services:
  workspace:
    image: allape/gophash:latest
    volumes:
      - ..:/workspace:cached
    ports:
      - "8080:8080"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
